import { useState, useEffect } from 'react';
import QRCode from 'qrcode';
import { getSurveyRoom } from '../api.js';
import { buildJoinLandingUrl } from '../gameLaunch.js';

const POLL_INTERVAL_MS = 1500;
const POLL_TIMEOUT_MS = 90000; // give the WebGL build ample time to load and create the room

// Shown after the professor clicks "Host Game". The room code is generated by the WS server when
// the (prebuilt) Unity build creates the room, so the web-app can't know it up front — it polls
// GET /api/game/survey-room/:surveyId until the room appears, then renders the student join link
// and a QR code that encodes it. Rendered as a modal overlay; closing only dismisses the panel
// (it never closes the running game room).
export default function HostRoomPanel({ surveyId, onClose }) {
  const [roomCode, setRoomCode] = useState(null);
  const [status, setStatus] = useState('waiting'); // 'waiting' | 'ready' | 'timeout'
  const [qrDataUrl, setQrDataUrl] = useState('');
  const [copied, setCopied] = useState(false);
  // Bumping this re-arms the poll effect (Retry) without duplicating the polling logic.
  const [attempt, setAttempt] = useState(0);

  const joinUrl = roomCode ? buildJoinLandingUrl(roomCode) : '';

  // Poll until the room exists or we time out. A self-scheduling timeout (not setInterval) avoids
  // overlapping in-flight requests, and the `cancelled` flag stops everything on unmount.
  useEffect(() => {
    let cancelled = false;
    let timer = null;
    const startedAt = Date.now();

    async function poll() {
      const res = await getSurveyRoom(surveyId);
      if (cancelled) return;
      if (res.success && res.data?.exists && res.data.roomCode) {
        setRoomCode(res.data.roomCode);
        setStatus('ready');
        return;
      }
      if (Date.now() - startedAt >= POLL_TIMEOUT_MS) {
        setStatus('timeout');
        return;
      }
      timer = setTimeout(poll, POLL_INTERVAL_MS);
    }

    poll();
    return () => { cancelled = true; if (timer) clearTimeout(timer); };
  }, [surveyId, attempt]);

  // Regenerate the QR whenever the encoded link changes.
  useEffect(() => {
    if (!joinUrl) { setQrDataUrl(''); return; }
    let cancelled = false;
    QRCode.toDataURL(joinUrl, { width: 240, margin: 1 })
      .then(url => { if (!cancelled) setQrDataUrl(url); })
      .catch(() => { if (!cancelled) setQrDataUrl(''); });
    return () => { cancelled = true; };
  }, [joinUrl]);

  function handleRetry() {
    setRoomCode(null);
    setStatus('waiting');
    setAttempt(a => a + 1);
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(joinUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const input = document.querySelector('.host-room-url');
      if (input) {
        input.select();
        document.execCommand('copy');
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }
  }

  return (
    <div className="host-room-overlay" onClick={onClose}>
      <div className="host-room-panel" onClick={e => e.stopPropagation()}>
        <button className="host-room-close" onClick={onClose} aria-label="Close">×</button>
        <h2>Student Join Link</h2>

        {status === 'waiting' && (
          <div className="host-room-waiting">
            <span className="host-room-spinner" aria-hidden="true"></span>
            <p>Starting the game room… the link and QR code will appear once the game connects.</p>
          </div>
        )}

        {status === 'timeout' && (
          <div className="host-room-waiting">
            <p>Couldn't detect the game room yet. Make sure the game tab finished loading, then retry.</p>
            <button className="btn-secondary btn-small" onClick={handleRetry}>Retry</button>
          </div>
        )}

        {status === 'ready' && (
          <div className="host-room-ready">
            <p className="host-room-code">Room Code <strong>{roomCode}</strong></p>

            {qrDataUrl && (
              <img className="host-room-qr" src={qrDataUrl} alt={`QR code for room ${roomCode}`} width={240} height={240} />
            )}

            <p className="host-room-hint">Students scan the QR code or open this link:</p>
            <div className="host-room-link-row">
              <input
                type="text"
                className="host-room-url"
                value={joinUrl}
                readOnly
                onClick={e => e.target.select()}
              />
              <button onClick={handleCopy} className="btn-secondary btn-small">
                {copied ? 'Copied!' : 'Copy Link'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
